services:
    sylius.form.type.gateway_configuration.payzen:
        class: Kiboko\SyliusPayzenBundle\Form\Type\PayzenGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: payzen, label: sylius.payzen_gateway_factory.payzen_checkout }
            - { name: form.type }

    kiboko_sylius_payzen_bundle.action.convert_payment:
        public: true
        class: Kiboko\SyliusPayzenBundle\Action\ConvertPaymentAction
        tags:
            - { name: payum.action, factory: payzen, prepend: true }
